// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNAW1KUEEHkhQ-o1rNeUC1OEYqZQaxF9c',
    appId: '1:209398750917:web:5445fca9c323187ffcdaac',
    messagingSenderId: '209398750917',
    projectId: 'flutter-firebase-tutoria-6c301',
    authDomain: 'flutter-firebase-tutoria-6c301.firebaseapp.com',
    storageBucket: 'flutter-firebase-tutoria-6c301.firebasestorage.app',
    measurementId: 'G-8D6852ER0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjan9TSYQrNF0Qqemd6b-s_6iLzM0vvLU',
    appId: '1:209398750917:android:2848b64b89388b45fcdaac',
    messagingSenderId: '209398750917',
    projectId: 'flutter-firebase-tutoria-6c301',
    storageBucket: 'flutter-firebase-tutoria-6c301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClIIido45bmefBPWa6MIFhI4Eckoq6Pjk',
    appId: '1:209398750917:ios:e872c483a551b5ecfcdaac',
    messagingSenderId: '209398750917',
    projectId: 'flutter-firebase-tutoria-6c301',
    storageBucket: 'flutter-firebase-tutoria-6c301.firebasestorage.app',
    iosBundleId: 'com.example.contentGenerator',
  );
}
